learningUsers/basicApp/urls.py
from django.conf.urls import url
from basicApp import views

#templateURLS
app_name = 'basicApp'

urlpatterns = [
    url(r'^$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user_login'),
]

learningUsers/learningUsers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basicApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^basic/', include('basicApp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^secret/$', views.special, name='special')
]

learningUsers/basicApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class userProfile(models.Model):
    """Model definition for userProfile."""
    
    # TODO: Define fields here
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="profile_pics", blank = True)
    portfolio_site = models.URLField(blank = True)

    def __str__(self):
        """Unicode representation of userProfile."""
        return self.user.username

learningUsers/basicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicApp import models

class userForm(forms.ModelForm):
    """Form definition for user."""
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        """Meta definition for userform."""

        model = User
        fields = ('username','email','password')


class userProfileForm(forms.ModelForm):
    """Form definition for userProfile."""
    
    class Meta:
        """Meta definition for userProfileform."""

        model = models.userProfile
        fields = ('portfolio_site', 'profile_pic')

learningUsers/basicApp/views.py
from django.shortcuts import render
from basicApp import forms
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def index(request):
    return render(request, "basicApp/index.html")

def register(request):

    registered = False
    if request.method == "POST":
        user_form = forms.userForm(data = request.POST)
        user_profile = forms.userProfileForm(data = request.POST)

        if user_form.is_valid() and user_profile.is_valid():
            user = user_form.save()
            user.set_password(user.password) #Hashing the password
            user.save()
            profile = user_profile.save(commit=False)
            profile.user = user #Actualizes the 1-1 relationship
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, user_profile.errors)
    else:
        user_form = forms.userForm()
        user_profile = forms.userProfileForm()

    return render(request, 'basicApp/registration.html', {'user_form':user_form,
                                                           'user_profile':user_profile, 
                                                           'registered':registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        #Django authentication
        user = authenticate(username=username, password=password) 
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Login failed!")
            print("username: {}, password: {}".format(username,password))
            return HttpResponse("Invalid username/password")
    else:
        return render(request, "basicApp/login.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Im secret")

learningUsers/templates/basicApp/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        
        {% block title %}
            
        {% endblock title %}
                
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="main.js"></script>
    <script
			  src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			  crossorigin="anonymous"></script>
</head>
<body>
    <!-- Image and text -->
    <nav class="navbar navbar-light bg-light navbar-default navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            <ul class="nav navbar-nav ml-auto">                  
                <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
                <li class="nav-item"><a href="{% url 'basicApp:register' %}" class="nav-link">Register</a></li>
                
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'special' %}" class="nav-link">Secret Page</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Log Out</a></li>                    
                {% else %}
                    <li class="nav-item"><a href="{% url 'basicApp:user_login' %}" class="nav-link">Log In</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>
    <div class="container">
        
        {% block body_block %}
            <!-- anything outside will be inherited -->
        {% endblock body_block %}
            
    </div>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

learningUsers/templates/basicApp/index.html
{% extends "basicApp/base.html" %}

{% block title %}
    Home
{% endblock title %}
{% block body_block %}
    <div class="jumbotron">
        <h1 class="display-4">Django Level Five</h1>
    </div>
{% endblock body_block %}
        

learningUsers/templates/basicApp/login.html
{% extends "basicApp/base.html" %}


{% block title %}
    Log In
{% endblock title %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Please log in!</h1>
        <form method="POST" action="{% url 'basicApp:user_login' %}">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" placeholder="Enter your username" name="username"> 
                <label for="password">Password</label>
                <input type="password" name="password">
                <input type="submit" class="btn btn-default" value="Log In">
                {% csrf_token %}
            </div>
        </form>
    </div>
{% endblock body_block %}
    

learningUsers/templates/basicApp/registration.html
{% extends "basicApp/base.html" %}
{% load staticfiles %}


{% block body_block %}
    <div class="jumbotron">
        
        {% if registered %}
            <h1>Thank's for registering!</h1>
        {% else %}
            <h1>Register Here</h1>
            <h3>Fill out the form:</h3>
            <form method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    {{ user_form.as_p }}
                    {{ user_profile.as_p }}
                    {% csrf_token %}
                    <input class="btn btn-default" type="submit" value="Submit">
                </div>
            </form>
        {% endif %}
            
    </div>
    <script>$('input').addClass("form-control")</script>
{% endblock body_block %}
    